kind: Service
apiVersion: v1
metadata:
  name: pelican-service
spec:
  selector:
    app: pelican
    release: production
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      name: http
  type: NodePort
